### ISSUE TITLE
QGIS Plugging- UMEP

### ISSUE THREAD

**Issue by 212337Rnt** [UMEP-dev/UMEP-Docs#11]
This tool has moved to UMEP for processing, available via the QGIS Plugin Manager. Visit our online manual for more information.

**Comment by ragini9m** [comment]
I am facing the same issue.

**Comment by biglimp** [comment]
Not an issue. I am closing. Just download UMEP for Processing from the Plugin Manager in QGIS.

**Comment by ragini9m** [comment]
I have already installed both the UMEP Plugins
